type: general
key: alliander
url: http://www.alliander.nl
description_en: Alliander is the largest grid management company in the Netherlands.
  Alliander plays an important role in the energy transition by facilitating developments
  such as decentralized energy generation, but also by constructing networks for electric
  transport and co-initiating the Energy Transition Model.
country: nl
description_nl: Alliander is het grootste netwerkbedrijf van Nederland. Alliander
  vervult een belangrijke rol in de energietransitie. Als facilitator voor ontwikkelingen
  als decentrale energieopwek, maar ook als realisator voor de netwerken van elektrisch
  vervoer én mede-inititiatiefnemer van het energietransitiemodel.
