type: general
key: amsterdam
url: http://www.amsterdam.nl
description_en: By making connections between strong and high-potential industries,
  innovative initiatives can flourish. The municipality of Amsterdam dedicates herself
  to this cause in association with her partners.
country: nl
description_nl: Door het maken van verbindingen tussen sterke en kansrijke sectoren
  kunnen innovatieve initiatieven groeien. De gemeente Amsterdam zet zich hier samen
  met haar partners voor in.
