type: knowledge
key: atkearney
url: http://www.atkearney.nl
description_en: A.T. Kearney is an international strategy consulting firm committed
  to sustainability. Our global Utilities Practice works with industry leaders that
  seek to take advantage of the opportunities the energy markets offer.
country: nl
description_nl: A.T. Kearney is een internationale strategieconsultingfirma die gecommiteerd
  is aan duurzaamheid. Onze Utilities Practice is over de gehele wereld actief en
  werkt met 'captains of industry' die op zoek zijn naar een leidende rol in de kansen
  die de energiesector biedt.
