type: education
key: belevenisonderwijs
url: http://www.klimaatuitdagingen.nl
description_en: Education partner. Click to visit the Belevenisonderwijs website.
country: nl
description_nl: Belevenisonderwijs streeft naar het verkrijgen van draagvlak in
  de samenleving voor alle veranderingen die voortvloeien uit de klimaatveranderingen.
  Denk aan water, energie, klimaat, gedrag, natuur, milieu. Belevenisonderwijs ontwikkelt
  lesmateriaal, practicummaterialen, projectdagen, excursies voor het onderwijs. Regelmatig
  brengt zij jongeren in contact met burgers. In gesprek met huiseigenaren tijdens
  het maken van warmtefoto's, of tijdens het schouwen van de sloten..
