type: knowledge
key: ce_delft
url: http://www.cedelft.eu
description_en: CE Delft supplies information for the Energy Transition Model and
  helps many of the partners with research and consultancy in the fields of energy,
  environmental policy and transport. See our company website
country: nl
description_nl: CE Delft levert informatie voor het Energietransitiemodel and helpt
  veel van haar partners met onderzoek en advies op het gebied van energie, klimaatbeleid
  en transport. Bekijk ook de website van ons bedrijf.
