type: knowledge
key: clingendael
url: http://www.clingendael.nl/
description_en: The Clingendael International Energy Programme (CIEP) makes a fundamental
  contribution to the public debate on international politics and economic developments
  in the energy sector (oil, gas and electricity). CIEP aims to examine the international
  political and economic drivers and consequences of the envisaged global energy transition.
country: nl
description_nl: Het Clingendael International Energy Programme (CIEP) tracht door
  middel van onderzoek, publicaties en bijeenkomsten een fundamentele bijdrage te
  leveren aan het publieke debat omtrent internationale politiek en economische ontwikkelingen
  in de energiesector (olie, gas en elektriciteit).
