type: general
key: delta
url: http://www.delta.nl
description_en: Delta is a full-service provider in the field of energy, infrastructure,
  environmental services, internet and telecom. Delta provides a unique service concept
  that meets a need for comfort and ease.
country: nl
description_nl: Delta is een full service dienstverlener op het gebied van energie,
  infrastructuur en milieudiensten, internet en telecom. Delta biedt een uniek dienstverleningsconcept
  dat tegemoet komt aan de behoefte aan gemak.
