type: knowledge
key: ecn
url: http://www.ecn.nl/nl/units/ps/themas/energie-en-emissiescenarios/
description_en: The Energy research Center of the Netherlands is the largest institute
  on energy research in the Netherlands.
country: nl
description_nl: Het Energieonderzoek Centrum Nederland (ECN) is het grootste onderzoeksinstituut
  in Nederland op energiegebied.
