type: knowledge
key: ecofys
url: http://www.ecofys.com
description_en: Ecofys provides knowledge and data for the Energy Transition Model.
  Ecofys creates smart, effective, practical and sustainable solutions for and with
  public and corporate clients all over the world.
country: nl
description_nl: Ecofys levert kennis en data for het Energietransitiemodel. Ecofys
  creëert slimme, effectieve, praktische en duurzame oplossingen voor en met publieke
  en private partijen over de hele wereld.
