type: general
key: eneco
url: http://www.eneco.nl
description_en: Eneco is one of the leading power companies in the Netherlands. It
  pursues an international, integrated distribution strategy with a focus on production,
  transport, trade, delivery and metering of energy (electricity, gas en heat) and
  related products and services.
country: nl
description_nl: Eneco is een van de toonaan-gevende energiebedrijven in Nederland.
  Het voert een internationale, geïntegreerde distributiestrategie en richt zich op
  productie, transport, handel, levering en meting van energie (elektriciteit, gas
  en warmte) en daaraan gerelateerde producten en diensten.
