type: education
key: energyvalley
url: http://www.energyvalley.nl
description_en: Education Partner. Click here to visit the Energy Valley website
country: nl
description_nl: De stichting Energy Valley bestaat sinds 2003 en is een netwerkorganisatie
  die met publieke en private partners invulling geeft aan de regionale groeikansen
  van de energiesector. De stichting is intermediair om projecten te versnellen, kennisuitwisseling
  te bevorderen en de noordelijke energieregio te versterken.
