type: general
key: enexis
url: http://enexis.nl
description_en: Enexis (formerly Essent Networks) manages the energy grid in the North,
  East and South of the Netherlands. We create an ever better, smarter and more efficient
  network and use our leading role to stimulate innovation and sustainable solutions.
  We therefore support the development of this model.
country: nl
description_nl: Enexis (vroeger Essent Netwerk) beheert het energienetwerk van Noord-,
  Oost- en Zuid-Nederland. We maken het netwerk steeds beter, slimmer en efficiënter.
  In onze leidende rol stimuleren we innovatie en duurzame oplossingen. Wij ondersteunen
  daarom graag de ontwikkeling van dit Energietransitiemodel.
