type: general
key: eon
url: http://www.eon-benelux.com
description_en: E.ON Benelux produces and supplies electricity, heat and gas to private
  customers and ranks among the biggest suppliers to the corporate market in the Netherlands.
  The company has some 1900 MW capacity in place in South Holland province, mainly
  in the Maasvlakte area. Construction of a new 1100MW plant is underway at this location. E.ON
  Benelux also has power plants in Belgium with some 940 MW capacity in place at Vilvoorde
  and Langerlo (Genk). We are active in the business segment of this market. E.ON
  Benelux has around 900 personnel. The head office is in Rotterdam.
country: nl
description_nl: E.ON Benelux produceert en levert elektriciteit, warmte en gas aan
  particuliere klanten en is in Nederland een van de grootste energieleveranciers
  voor de zakelijke markt. Het bedrijf heeft circa 1900 MW opgesteld vermogen in Zuid-Holland,
  met name op de Maasvlakte. Op die lokatie is ook een nieuwe 1100MW centrale in aanbouw.
  Tevens heeft E.ON Benelux centrales in België met een opgesteld vermogen van circa
  940 MW in Vilvoorde en Langerlo (Genk). In deze markt zijn we actief in het zakelijke
  segment. Bij E.ON Benelux werken circa 900 medewerkers. Het hoofdkantoor staat in
  Rotterdam.
