type: education
key: epn
url: http://www.epn.nl
description_en: Education partner. Click to visit the EPN website.
country: nl
description_nl: EPN is specialist in het ontwikkelen van leermiddelen voor alle
  niveaus van het voortgezet onderwijs. Onze lesmethoden staan al jarenlang garant
  voor goed en plezierig onderwijs. Zo bestaat de methode Getal & Ruimte voor wiskunde
  al meer dan 40 jaar! De aardrijkskundemethode buitenland van EPN heeft een
  actueel project ontwikkeld over energietransitie. In dit project wordt gebruik gemaakt
  van het Energietransitiemodel.
