type: general
key: essent
url: http://essent.nl
description_en: Essent contributes to the Energy Transition Model with respect to
  content by validating the market and production possibilities and helping to keep
  all information up to date.
country: nl
description_nl: Energiebedrijf Essent draagt inhoudelijk bij aan het Energietransitiemodel
  door gegevens van markt- en de productiemogelijkheden te valideren en up to date
  te houden.
