type: general
key: gasterra
url: http://www.gasterra.nl
description_en: GasTerra is an international company trading in natural gas. The
  company recognises the importance of the transition to a sustainable energy supply
  and initiates projects in that context.
country: nl
description_nl: GasTerra is een internationaal opererende handelsonderneming in aardgas.
  De onderneming onderkent het belang van het transitietraject naar een duurzame energiehuishouding
  en initieert projecten in dit kader.
