type: education
key: hpbodeb
url: http://plado.nl/category/themas/duurzame-energie-de-beroepskolom
description_en: no description
country: nl
description_nl: In het project Duurzame Energie in de Beroepskolom (DEB) staat de
  onderwijsvernieuwing voor duurzame energie in het beroepsonderwijs centraal. Drie
  MBO en drie HBO instellingen werken daarin nauw samen met het bedrijfsleven. Het
  project wordt gesubsidieerd vanuit Hèt Platform Beroepsonderwijs (HPBO).
