type: education
key: jouwenergievanmorgen
url: http://www.jouwenergievanmorgen.nl
description_en: The faculty of Mathemetics and Natural Sciences of the University
  of Groningen and GasTerra challenge modern youngsters to work on useable solutions
  for the energy transition. This happens in and around the Jouw Energie van Morgen
  Truck. A traveling labaratory. An inspiring lecture room. With which we drive to
  VWO schools in the Netherlands to explore the future with you
country: nl
description_nl: De Faculteit Wiskunde en Natuurwetenschappen van de Rijksuniversiteit
  Groningen en GasTerra dagen jongeren van nu uit om mee te werken aan bruikbare oplossingen
  voor de energietransitie. Dit gebeurt in en rond de Jouw Energie van Morgen truck.
  Een rondreizend laboratorium. Een inspirerende collegeruimte. Waarmee we langs de
  VWO-scholen in Nederland trekken om met jou de toekomst te verkennen.
