type: knowledge
key: kema
url: http://www.dnvkema.com
description_en: "DNV KEMA Energy & Sustainability, an objective and impartial knowledge-based
  company, provides advice and support organizations along the energy value chain:
  producers, suppliers & end-users of energy, equipment manufacturers, as well as
  government bodies, corporations and non-governmental organizations."
country: nl
description_nl: "DNV KEMA Energy & Sustainability is een objectief en onpartijdig
  energiekennisbedrijf dat advies en ondersteuning biedt aan organisaties in de energiewaardeketen:
  producenten, leveranciers & eindgebruikers van energie, fabrikanten van apparatuur,
  overheidsinstanties, bedrijven en niet-gouvernementele organisaties."
