type: general
key: logica
url: http://www.logica.nl
description_en: Logica is an international ICT-service provider with more than 20
  years of experience in the utility industry. Logica has a leading role in the development
  or integration of innovative solutions.
country: nl
description_nl: Logica is een internationale ICT-dienstverlener met meer dan 20 jaar
  ervaring in de energiewereld. Logica heeft een toonaangevende rol in het ontwikkelen
  en integreren van innovatieve oplossingen.
