type: knowledge
key: milieucentraal
url: http://www.milieucentraal.nl
description_en: All you want to know about saving energy and the environment
country: nl
description_nl: Alles over energie en milieu in het dagelijks leven
