type: education
key: nyenrode
url: http://www.nyenrode.nl
description_en: Nyenrode Business University developed the Energy Mini MBA in which
  the Energy Transition Model serves as an integral element.
country: nl
description_nl: Nyenrode Business Universiteit heeft de Energy Mini MBA ontwikkeld,
  waarin het Energietransitiemodel als integraal onderdeel behandeld wordt.
