type: general
key: shell
url: http://www.shell.nl
description_en: Shell is a global group of energy and petrochemicals companies. Shell
  helps to meet the world's growing demand for energy in economically, environmentally
  and socially responsible ways.
country: nl
description_nl: Shell is een wereldwijde groep energie- en petro- chemiebedrijven.
  Wij willen op economisch, milieutechnisch en maatschappelijk verantwoorde manieren
  helpen om in de groeiende energiebehoefte van de wereld te voorzien.
