type: general
key: stedin
url: http://www.stedin.net
description_en: Stedin provides safe and continuous transport of gas and electricity
  to more than two million customers in and around three of the four big cities in
  Randstad, as well as the Rotterdam harbour area.
country: nl
description_nl: Stedin zorgt voor een veilig en continu transport van gas en elektriciteit
  naar ruim twee miljoen klanten in en rondom drie van de vier grote steden in de
  Randstad en het Rotterdamse havengebied.
