type: general
key: tennet
url: http://www.tennet.nl
description_en: With its high-quality transmission grid and customized approach,
  TenneT offers and develops a comprehensive range of transmission and system services,
  while also supplying services in support of free-market operation and a sustainable
  energy supply system.
country: nl
description_nl: Met een kwalitatief hoogwaardig transportnet en toegesneden dienstverlening
  biedt en ontwikkelt TenneT energiemarkt een breed aanbod van transport- en systeemdiensten
  en levert TenneT diensten die de marktwerking en de ontwikkeling van een duurzame
  energievoorziening stimuleren.
