type: education
key: uitlegtekst
url: http://www.uitlegentekst.nl
description_en: Uitleg & tekst makes informative and educational products using both
  new and traditional media.
country: nl
description_nl: Uitleg & tekst verzorgt informatieve en educatieve producten voor
  zowel nieuwe als traditionele media.
