type: general
key: unetovni
url: http://www.unetovni.nl
description_en: UNETO-VNI is the Dutch trade organization for entrepreneurs in installation
  and technical retail businesses. The association represents over 5,300 installation
  businesses with a turnover of 10.5 billion Euros.
country: nl
description_nl: UNETO-VNI is de ondernemersorganisatie voor de installatiebranche
  en de technische detailhandel. De vereniging vertegenwoordigt ruim 5.300 installatiebedrijven
  met een totale omzet van 10,5 miljard euro.
