type: general
key: vshanab
url: http://www.vshanab.nl
description_en: Visser & Smit Hanab develops, builds and maintains connections,
  networks and installations for water and energy.
country: nl
description_nl: Visser & Smit Hanab ontwikkelt, bouwt en onderhoudt verbindingen,
  netwerken en installaties voor water en energie.
