type: knowledge
key: warmtepompplein
url: http://www.warmtepompplein.nl
description_en: Knowledge partner. Click to go to website.
country: nl
description_nl: Warmtepompplein.nl is een onafhankelijk informatieportaal over warmtepompen
  voor verwarming, koeling en warm tapwater in woningen. Dit portaal wil voorzien
  in informatiebehoefte naar warmtepompen in de breedste zin van het woord.
