---
key: vermeend
name: Willem Vermeend
organization: Universiteit Maastricht
function:
  nl: Professor Fiscale Economie en Europees Fiscaal Recht
  en: Professor Fiscal Economics and European Fiscal Law
scenario_id: 147683
