name:       Alexander Wirtz

key:        alex

title:      Partner

status:     active

social:     
  linkedin: http://www.linkedin.com/in/alexanderwirtz

education:
  - PhD Physics
  - MSc Chemistry

experience:
  - Strategy Consultant at Quintel Strategy Consulting
  - PhD student at Leiden at Leiden University

questions:
  -
    q: What makes your heart beat faster?

    a:
      My two-year-old daughter explaining the facts of life to her stuffed 
      animals before she falls asleep.
      Good food and cooking it.
      Good coffee.
      Philosophy of any kind, but that of language in particular. 
      Beautiful and exact prose.
      Realizing you have mastered a foreign language to the point where 
      people laugh at your dinner party jokes.
  -
    q: What drives you crazy?

    a: 
      Still waaaay too many things, but I am working on that!
  -
    q: If an alien looked at the state of the earth as it is now, what would he think?

    a:
      Give it another 5 centuries or so and we will have the place to ourselves.
  -
    q: Tell us a fun fact...

    a:
      In logical theory not until the late 19th century did it become 
      possible to distinguish between the statements "All things have 
      an origin" and "All things have one (i.e. a single) origin". In 
      the Western world, this shortcoming was used as logical proof for 
      the existence of God by the most learned of people for almost two 
      millennia. In the end, logic prevailed...
  -
    q: What are your responsibilities at Quintel Intelligence?

    a: 
      I am responsible for energy research and the 'know-how' that the 
      Energy Transition Model is based on. I am also responsible for
      the quality of the coffee at our office, have a tendency to police company 
      spelling and check written documents, do the odd presentation or workshop
      and try and make sure I do most of the complaining around the office,
      so my colleagues do not have to. 
  -
    q: What do you respect most in people?
    
    a:
      Wisdom.
  -
    q: Who would you like to be for 24 hours?
    
    a: 
      Stevie Ray Vaughan, had he still been alive. Then I would try and 
      take his talents as a guitar player with me when I go back!
      
