name: Chael Kruip

key:  chael

title: Senior Modeler

status: active

social:
  github: http://github.com/chaelkruip
  linkedin: http://nl.linkedin.com/pub/chael-kruip/10/a85/241

education:
  - PhD Astronomy & Astrophysics
  - MSc Astronomy & Astrophysics
  - BSc Physics

experience:
  - Scientific programmer at Leiden University
  - PhD student at Leiden at Leiden University

questions:
  -
    q: What makes my heart beat faster...

    a:
      New experiences. I love to be surprised by people, impressions and ideas
      that are more than a simple extrapolation of my life so far.
      That and a good cigar.
  -
    q: What drives you crazy?

    a:
      Freezing YouTube videos, Windows Vista and, more generally, narrow mindedness.
  -
    q: What is the most useless piece of information I know...

    a:
      I know that Trypophobia is an irrational fear of clustered holes such as can be found
      in lotus seed pods, the Ampullae of Lorenzini in Sharks, enlarged pores of the skin etc.
      Also, I know quite a bit about Astronomy, which makes it useless almost by definition.
  -
    q: What is your favorite movie?

    a: |
      "Blade Runner" (1982) (closely followed by Tarkovski's "Stalker" (1979) 
      and "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb" (1964)).
  -
    q: Can you tell us a riddle?

    a: |
      Gargamel has captured Papa Smurf and threatens to feed him to Azrael (his cat) 
      unless the 100 remaining smurfs solve the following diabolical problem: 
      Each smurf is given a hat that is either red or white. 
      A smurf cannot see his own hat and does not know its color.
      They only know that there is at least one hat of each color. 
      The smurfs are forbidden to communicate in any way.
      Gargamel has instituted a strict curfew but allows the smurfs one meeting per day. 
      Smurfs that don't know their hats color must come to the meeting, 
      those who do must stay at home.
      How do the (admittedly brainy) smurfs find out the colors of their hats? 
      How many meetings does it take in the worst-case scenario?

