name: Chris Laumans

key: chris

title: Project Manager

status: active

social:
  linkedin: http://www.linkedin.com/in/chrislaumans

education:
  - MSc Human Movement Sciences (in progress)
  - MSc Sustainable Energy Technology
  - BSc Aerospace Engineering

questions:
  -
    q: Who is your inspiration?

    a:
      The Dalai Lama! I saw him once in Amsterdam and I think it is simply
      incredible how he carries an aura of happiness around and how even in light
      of everything that has happened to him and the people of Tibet 
      he seems capable of showing endless love and compassion.
  -
    q: What is your motto?

    a:
      Kaizen. This is a Japanese word that literally translates to "change for
      the better", but it is much more than that. The word was used by Samurai
      as one of their guiding principles and can better be described as a
      "constant and never ending improvement." It is the aim to improve yourself 
      each and every day, one step at a time.
      It speaks so much to me because I think this is something we sometimes
      forget when we fall into the rhythm of routine. I admire the focus with which
      the Samurai applied this philosophy.
  -
    q: Why did you choose Quintel Intelligence?

    a:
      It is a small company with many opportunities, friendly colleagues that are
      open and accessible, and the work is challenging and motivating. Being able 
      to work on very relevant, global issues is a very rewarding experience.
  -
    q: What is your favorite quote?

    a:
      The Iron is the best antidepressant I have ever found. There is no better 
      way to fight weakness than with strength. Once the mind and body have been 
      awakened to the their true potential, it's impossible to turn back.

      The Iron never lies to you. You can walk outside and listen to all kinds 
      of talk, get told that you're a god or a total bastard. The Iron will always
      kick you the real deal. The Iron is the great reference point, the all-knowing
      perspective giver. Always there like a beacon in the pitch black.

      I have found the Iron to be my greatest friend. It never freaks out on me, 
      never runs. Friends may come and go. But two hundred pounds is always two 
      hundred pounds.
      Henry Rollins
  -
    q: What do you like to do outside of working hours?

    a:
      I like to lift heavy stuff. Powerlifting and Olympic weight lifting (Don't 
      get this confused with that I-like-to-wear-speedos-on-stage-and-my-chest-is-
      to-big-for-my-shirt bodybuilding stuff). At the end of a long day it helps me
      clear my mind and I love the challenge, it is always just me against myself. 
      I decide whether I win or lose. I always win.
  -
    q: What makes your heart beat faster?

    a:
      Breaking a personal record and watching others do the same.
