name: Dennis Schoenmakers

key: dennis

title: Partner

status: active

social:
  twitter: http://twitter.com/iShoeMaker
  github: http://github.com/dennisschoenmakers
  linkedin: http://www.linkedin.com/pub/dennis-schoenmakers/a/62a/9a

education:
  - MSc Finance Economics
  - MSc Behavior Economics
  - BA Spanish language and literature

experience:
  - Strategy Consultant at Quintel Strategy Consulting (now AT Kearney)
  - Reporter Quote Magazine

questions:
  -
    q: What are your responsibilities at Quintel Intelligence?

    a:
      As CTO I am responsible that the ETM keeps working
      while we constantly refine and add new things to it. I try to make sure
      that everything looks pretty, that the team stays happy and on top of the
      newest cutting edge technology and that we keep working intimately
      together. As CFO I am financially responsible for the company, trying
      not to spend too much, and not to invest too little.
  -
    q: What do you respect most in people?

    a:
      Creativity and fearlessness.

  -
    q: What makes your heart beat faster?

    a:
      Seeing my two children enjoying every inch and every minute of their
      lives, a great speech, wind speed of 20 knots at sea with waves of one a
      a half meter.
  -
    q: What would you bring to a deserted island?

    a:
      I would bring a book on the race to the South Pole, when Shackleton,
      Scott and Anderson all tried to be the first to reach it. Shackleton
      got within 100 miles, but had to turn back, Scott reached it to find
      out that Anderson beat him by a mere five weeks. On the way back, he
      and his team perished due to ill preparations. And oh yes, I would bring
      a nice catamaran sailing boot, so I could get off the island in style
      once fed up with it.
  -
    q: What is the best team experience I've had in my work so far...

    a:
       There are so many... Every time we - as a team - tackled a great
       challenge.
  -
    q: What is your favorite quote?

    a:
      One day Alice came to a fork in the road and saw a Cheshire cat in a
      tree. Which road do I take? she asked. Where do you want to go? was his
      response. I don't know, Alice answered. Then, said the cat, it doesn't
      matter.
