name: Jeroen Alsem

key: jeroen

title: Intern

status: active

social:
    linkedin: http://www.linkedin.com/pub/jeroen-alsem/2a/912/b06

education:
  - MSc Systems Engineering, Policy Analysis and Management
  - BSc Systems Engineering, Policy Analysis and Management

questions:
  -
    q: What are your responsibilities at Quintel Intelligence?
    a:
      As a graduate intern I am working on my master thesis. This means that I
      do scientific research which is used in practice. The work and research
      that I do is important for Quintel Intelligence, since it contributes to
      improving the ETM.
  -
    q: What do you respect most in people?
    a: Respect for others, including me.
  -
    q: What makes your heart beat faster?
    a:
      Being coach of a rowing team watching my team struggle and giving their
      very best as they are heading for the finish of a race (and of course they
      win the race!).
  -
    q: What would you bring to a deserted island?
    a: A snorkling outfit, so that I can find Nemo.
