name: Jesse Kerkhoven

key: jesse

title: Developer

status: active

education:
  - Propaedeutic IT

experience:
  - Programming for the web since 2007
  - Working for Quintel since 2009
  - Founder and owner of start-up "Green-A-Tech" smart solutions

questions:
  - q: What countries would you like to visit? (so that you can add it to the
       ETM of course.. )
    a: I would like make a world trip in the coming years
       to get a glimpse of the culture of various countries.
       And of course to get away, to be out there and free.

  - q: Who would you most like to show the ETM to?
    a: I would like to show the ETM to Neelie Kroes,
       so it becomes known in European politics and education.

  - q: What motivates you in your work?
    a: The fact that a lot of people don't know what energy transition is. 
       So there still is a lot of work to do to inform the world about energy
       transition, to motivate them and let them think about energy transition.

  - q: What do you add in your daily life to energy transition?
    a: Working in a local organization in my city which is engaged to create
       an energy self-sufficient community, and that acts as a knowledge center
       for communities who wish to follow.

  - q: What drives you crazy?
    a: Systems that don't work, don't function well or applications that
       are not easy to use.
