name: John Kerkhoven

key: john

title: Managing Partner

status: active
  
education:
  - PhD in Marketing, Operations Research and Computer Science

experience:
  - Managing director at Quintel Strategy Consulting (now AT Kearney)
  - Partner at Arthur D. Little

questions:
  -
    q: What do you do in your daily life to contribute to the energy transition?

    a:
      Our family lives in an energy neutral house, we have an electric car that
      charges using solar energy, we only eat plants and we have a vegetable 
      garden.
  -
    q: Why did you choose Quintel Intelligence?

    a:
      The subject of energy transition highly intrigued me in 2007. The only
      way for me to properly research the subject and have others share in our
      findings was to found Quintel Intelligence.
  -
    q: What motivates you in your work?

    a:
      Raising collective awareness about the necessity and possibilities to
      change to a happy and sustainable lifestyle.
  -
    q: What makes your heart beat faster?

    a:
      Many things. A smile from my wife, a technical solution that outperforms
      its spec, a person that decides to adapt his lifestyle etcetera.
  -
    q: What I like to do outside working hours

    a:
      Optimize our house from energy neutral to energy self-sustaining and to
      learn how to optimize the produce from our vegetable garden.
  -
    q: Which problem would you like to solve?

    a:
      How to get our electric car to act as a backup for the house. And to make
      a food transition model that helps people to understand what is healthy
      food with minimal impact on the planet.
  -
    q: What are your responsibilities at Quintel Intelligence?

    a:
      As managing partner I am responsible for the long term strategy of our
      firm as well as the day to day relationships with our partners. I also
      give lectures and speeches and write columns and articles on the subject
      of energy transition.
  -
    q: Where do you see yourself in 5 years?

    a:
      Happy. Working as managing partner of this firm. As a hobby one or more
      steps closer to energy and food self sufficiency at home. In short pretty
      much the same as now.
  -
    q: Where do you see the ETM in 5 years?

    a:
      A European standard for free information and calculations on the subject
      of energy and food transition.
  -
    q: Who would you most like to show the ETM to?

    a:
      Steve Jobs to get his feedback. But that is rather difficult these days.
  -
    q: If an alien looked at the state of the earth as it is now, what would he think?

    a:
      Why do these people destroy their own home planet slowly but surely?
  -
    q: What is your favorite thing in the world?

    a:
      Nature.
  -
    q: Can you tell us a riddle?

    a:
      Together with Alex and Dennis, I am in the process of starting a new firm 
      that invests in new Energy Technologies that have just come out of the lab. We
      are working with two companies that could be on the verge of turning the
      energy world upside down.
  -
    q: What drives you crazy?

    a:
      People that ignore the consequences of that which can be objectively
      measured. Ranging from young beautiful people that start to smoke to
      political leaders that think that climate change is nonsense.
