name: Joris Berkhout

key:  joris

title: Senior Modeler

status: active

social:
  github: http://github.com/jorisberkhout
  linkedin: http://nl.linkedin.com/in/jorisberkhout/

education:
  - PhD Physics
  - MSc Physics

experience:
  - Scientist and team leader at cosine Science & Computing BV
  - PhD student at Leiden University

questions:

  -
    q: Why did you choose Quintel Intelligence?

    a:
      Providing a reliable supply of energy for everybody without affecting the world around us to much is one of
      the biggest challenges of our time. Our Energy Transition Model is the ideal tool for understanding the complexity
      of this challenge and exploring solutions to it. By joining Quintel I will have a chance to contribute to the ETM and
      gain more insight in the energy system.

  -
    q: Which problem would you like to solve?

    a:
      Energy storage and energy distribution. We have plenty of ways to generate renewable energy, but getting it to the
      right place at the right time proves to be quite a challenge.

  -
    q: What are your responsibilities at Quintel Intelligence?

    a:
      As a modeler I am responsible for turning the vast amount of data that is available on the energy system into a
      comprehensible and easy to use model without losing the relevant details.

  -
    q: What makes your heart beat faster?

    a:
      Quite literally cycling. Whether it is climbing the Col de la Croix de Fer on my road bike or racing around the track in
      Noordwijkerhout on my mountain bike, I love raise my heartbeat on a bike.

  - 
    q: What is your favourite TV show?

    a:
      QI. The fact that Quintel Intelligence shares its initials with this brilliant BBC show cannot be a coincidence.
