name: Julie Campistany

key: julie

title: Intern

status: inactive
  
social:
  linkedin: http://es.linkedin.com/pub/j%C3%BAlia-campistany-albareda/43/b47/19a

education:
  - Industrial Engineering, TU Delft
  - ETSEIB, Barcelona
  - Mechanical Engineering, TU Delft

questions:

  - q: What are your responsibilities at Quintel Intelligence?

    a:
      I belong to Quintel Intelligence as an intern and I am currently working
      on my Master Thesis. This academic research will contribute to the
      improvement of the ETM.

  - q: What drives you crazy?

    a: "In a negative way: Stupidity. In a positive way: Olives."

  - q: What makes your heart beat faster?

    a:
      Making my niece and my nephew laugh, performing on stage and in real
      life, the beginning of a new trip, meeting interesting people, and too much
      caffeine.

  - q: Tell us a fun fact.

    a:
      The first thing I had as a baby was coffee and the first thing I did was
      to 'steal' the doctor's stethoscope.
