name: Maria Tsagkaraki

key: maria

title: Energy Intern

status: active

social:
  github: https://github.com/mariatsagkaraki
  linkedin: http://dk.linkedin.com/in/mariatsagkaraki

education:
  - MSc Sustainable Energy Planning and Management
  - Diploma Environmental Engineer


experience:
  - Intern at Quintel Intelligence

questions:
  -
    q: Why did you choose Quintel Intelligence?

    a:
      Energy is an important factor in every aspect of our life, from covering our 
      daily needs to dealing with more complicated issues such as energy balance. 
      Choosing Quintel is a great opportunity for me to discover this complexity 
      and get a better understanding of the energy system. 
  -
    q: What are you responsibilities at Quintel Intelligence?

    a:
      I am responsible for researching the technical and cost parameters of all 
      technologies in the Energy Transition Model and documenting them in a 
      more useful and comprehensive way for researchers outside Quintel.

  -
    q: What motivates you in your work?

    a:
      The idea that the Energy Transition Model becomes more and more 
      advanced and realistic providing results for real everyday problems. 

  -
    q: What's your favorite movie?

    a:
      La vita è bella (1997) by Roberto Benigni

  -
    q: What's your favorite quote?

    a:
      Don't cry because it's over, smile because it happened.
