name: Mark den Heijer

key: mark

title: Project manager

status: active

social:
  linkedin: http://nl.linkedin.com/in/markdenheijer

education:
  - MSc Applied Physics
  - BSc/MSc Physics

experience:
  - Researcher at Delft University of Technology
  - Teacher at Stichting Studiebegeleiding Leiden

questions:
  -
    q: What motivates you in your work?

    a:
      Solving complex problems, learning new things, and contributing to a
      better world. On a daily basis I mostly enjoy the lively discussions with
      colleagues!

  -
    q: What I like to do outside working hours

    a:
      Sailing! Whether it is racing a dinghy with trapeze and spinnaker,
      cruising on a yacht, or teaching newbies how to sail, I find it a
      pleasure to be out on the water and harness the energy of the wind.
      And...  it's 100% sustainable!

  -
    q: What makes my heart beat faster...

    a:
      "To learn, gain insight into, and experience how the world around us
      works. Not only nature and technology, but also: What makes people move?
      How does the economy (dis)function? Why is Africa poor and Europe rich?
      And what will happen in the future?"

  -
    q: What is your favorite quote?

    a:
      Make things as simple as possible, but not any simpler. (Although Albert
      E. did not phrase it this simple himself)


