name: Nikki Brormann

key: nikki

title: Office Manager

status: active

social:
  linkedin: nl.linkedin.com/in/nikkibrormann/
  twitter: twitter.com/GroenVuur

education:
  - Master's Applied Ethics
  - MA Design

experience:
  - "Freelancer @ Groen Vuur: I applied my analytical skills to provide context 
    and criteria in difficult and moral issues."
  - "Teacher @ Utrecht Art Academy (BA) and Sandberg Institute (MA):
    I teach research (related) classes at these higher art educations through
    which students are to develop their conceptual, research, analytical,
    writing and argumentation skills."

questions:
  -
    q: Why did you choose Quintel Intelligence?

    a:
      "Quintel’s ETM is a practical and objective tool that can be
      used in the most urgent issue of our time: energy management.
      I feel it is a very modern en valuable way of supporting
      difficult decision-making regarding our energy options.
      To be a part of that is why I chose Quintel Intelligence."
  -
    q: What motivates you in your work?

    a:
      "When I was 5 years old I wanted to become an inventor,
      at the age of 23 I graduated in applied ethics.
      These two professions share the same motivation:
      I love to solve hard and practical problems to make life easier
      for people and the world a better place."
  -
    q: What makes your heart beat faster?

    a:
      My partner, who keeps me sane. The sea and all the senses involved in
      its presence.
  -
    q: Who would you like to be for 24 hours?

    a:
      Hillary Clinton. I think she is an amazing woman,
      and I would love to know what it is like to be in such a
      respected yet tough position of power and I would ask
      all the influential people she knows difficult questions.
  -
    q: Which problem would you like to solve?

    a:
      Global injustice. I know the solution has to do with
      people taking responsibility and doing what is right.
      Knowing the answer will not solve the problem though.
  -
    q: What country would you like to visit?

    a:
      The place I’d like to visit most is Antarctica,
      which is not officially a country.
      Its nature, history and political/scientific relevance
      really appeals to me.
  -
    q: Who is your inspiration?

    a: 
      My grandmother, who is still critical at the age of 84
      and not afraid of a good challenge while remaining
      the most down to earth and funniest person I know.
      My mother, who is the embodiment of a strong woman with an
      incredible intuitive sense of life and reality.
  -
    q: What is your favorite thing in the world?

    a:
      Dancing with friends to good music on a hot summer day
      at an outdoors festival (such as Melt! or ITGWO).
