name: Paolo Zaccagnini

key: paolo

title: Developer

status: inactive

social:
  twitter: http://twitter.com/paozac
  github: http://github.com/paozac

education:
  - BD in French Literature

experience:
  - System Administrator at Kataweb
  - Programmer at Telecom Italia SpA
  - Programmer at Tiscali SpA
  - Programmer at InformaSistemi SpA

questions:
  -
    q: What I like to do outside working hours
    a: Reading, rock climbing and sleeping
  -
    q: What country would you like to visit?
    a: South Pacific islands and Patagonia
  -
    q: Who is your inspiration?
    a: Corto Maltese and climbing legend Walter Bonatti
  -
    q: What are your favorite movies?
    a: 3-Iron and The Royal Tenenbaums
