name: Sebastian Burkhard

key: sebi

title: Developer

status: inactive

social:
  twitter: http://twitter.com/hasclass
  github: http://github.com/hasclass

education:
  - MSc Commerce IT University of Zurich

questions:
  -
    q: Why did you choose Quintel Intelligence?
    a: |-
      Initially just to get a quick buck from a 3 month contract so I can escape poverty.
      Now I proudly accept the title "longest and smallest team member".

  -
    q: What is the best team experience I’ve had in my work so far...
    a: |-
      Driving to a client presentation through the Dutch Niemandsland, sitting in the backseat and fixing a bug last-minute over a
      slow and spotty 3G mobile connection with four cheering colleagues around me. Maybe not the best experience
      but definitely memorable.

  -
    q: "Who would you like to be for 24 hours?"
    a: |-
      Some corrupt, filthy rich person and legally transfer all his money to my secret Swiss bank account.

  -
    q: Who or what would I bring to an uninhabited island...
    a: |-
      A hammock and a canoe for upper-body workout and to get stuff from 7/11 on the neighbouring habitated island.
