name:       Susana Kind

key:        susana

title:      Energy Education Marketeer

status:     active

social:
  github: http://github.com/susanaa
  linkedin: nl.linkedin.com/in/susanakind

education:
  - MSc Sociology
  - BSc Social Work

experience:
  - Research Assistant at Erasmus University
  - Program Officer at Maatwerk bij Terugkeer and Beyond Borders

questions:
  -
    q: Why did you choose Quintel Intelligence?

    a:
       Developments in the energy system have one of the highest impacts on
       society and my background in social studies makes energy transition very
       relevant to me. I believe providing information and starting a dialogue
       are vital for people to be able to understand and deal with challenges 
       in this sector. Quintel’s mission, especially it's emphasis on education,
       is therefore very appealing to me.

  -
    q: What are your responsibilities at Quintel Intelligence?

    a:
       I am responsible for Quintel's educational program - my priority is to
       promote and publicise the ETM within the education sector. I ensure
       educational institutions are familiar with the ETM and assist them with
       implementing it in practical sessions. I also handle most of the relation
       management with education related contacts, arrange trainings and
       contribute to the development of the education website and materials.

  -
    q: What motivates you in your work?

    a:
       When I reach out to teachers and professors, explaining the ETM and they
       tell me “Why didn't I know about this before!?”. Their enthusiasm
       really motivates me to widen the ETM's impact within the education
       sector. It is great to know that with the ETM we can help teachers and
       professors introduce or broaden the theme of energy in their classes.
       Also hearing surprised reactions like the one above means there are 
       still a lot of people yet to be reached!

  -
    q: What is your favorite movie?

    a:
       I like old Italian movies such as "Il Sorpasso" (1962) by Dino Risi.

  -
    q: What makes your heart beat faster?

    a:
       Unraveling social misconceptions over dinner with friends.

  -
    q: What is your favorite quote?

    a:
       “Se podes olhar, vê. Se podes ver, repara.”
       Translates to
       “If you can look, see. If you can see, notice.”
       - José Saramago
