name:        Thomas Wilkinson

key:         thomas

title:       Developer Intern

status:      active

social:
  github: http://github.com/twilkinson573
  linkedin: https://www.linkedin.com/in/thomaswilkinson1

education:
  - BSc Bioarchaeology

experience:
  - Director at Generation i Ltd
  - CMO & Lead Writer at Beatz Magazine
  - Junior Account Executive at Accleris Marketing Communications

questions:
  -
    q: What makes your heart beat faster?

    a:
      Feeling myself noticably improving at something, whether it's my
      code, my Dutch, or my backhand.

  -
    q: What drives you crazy?

    a:
      The way many people will instantly dismiss what they read on the 
      internet as a lie, but automatically treat everything printed in a 
      newspaper as unquestionable objective truth. Also, the way 'child-proof'
      packaging seems to defeat me every time we meet.

  -
    q: What do you respect most in people?

    a:
      Confidence - the key to unlocking life's 'easy mode'.

  -
    q: Who or what would I bring to an uninhabited island?

    a:
      Being English I suppose suncream should be a priority. As for
      entertainment, an Ayn Rand novel and a set of weights would 
      probably be enough to keep me busy for a few years. I also wouldn't
      mind taking my guitar, after years of owning it just to look cool it's 
      about time I started to get good with the old thing.

  -
    q: What is your favorite quote?

    a:
       Sometimes you win, and sometimes you learn.
       - Thomas Wilkinson

