name: Wouter Meyers

key: wouter

title: Project manager

status: active

social:
  twitter: http://twitter.com/woutermeyers
  linkedin: http://nl.linkedin.com/in/woutermeyers

education:
  - MSc Engineering and Policy Analysis
  - BSc Information Technology

experience:
  - Teacher and researcher at Delft University of Technology
  - Project Manager at Delft Centre for Entrepreneurship

questions:
  -
    q: What makes my heart beat faster...

    a:
      Experiencing new things, going to a new country, doing a new sport,
      learning a new skill, trying out a new food... Etc etc etc
  -
    q: Who would you like to be for 24 hours?

    a:
      Barack Obama. I would really like to stand in the shoes of the president
      of the USA for 24 hours to feel the enormous responsibilities he has to
      face every day.
  -
    q: If an alien looked at the state of the earth as it is now, what would he think?

    a:
      The way the universe works, I think there is very little chance aliens
      would be able to see what is happening on our little planet. Considering
      how lucky we are with fossil fuels and all kinds of rare metals I would
      also not expect them to be able to fly to us. That is why it is even more
      of a shame that we are wasting these precious resources...
  -
    q: What is your favorite movie?

    a:
      Fight Club. I am intrigued by the bleak worldview portrayed in the movie,
      even though it has a much happier ending than the book. Another movie that
      could one day be my favorite is The Fountain, but first I have to 
      figure it out completely...

