name: Wouter van Lelyveld

key: wvl

title: Modeler

status: active
  
social:
  linkedin: http://www.linkedin.com/pub/wouter-van-lelyveld/6/222/634
  facebook: http://www.facebook.com/WvanLelyveld
  github: http://github.com/WvanLelyveld

education:
  - BSc and MSc in Systems Engineering, Policy Analysis and Management (Delft University of Technology)
  - Semester at the School of Public and Environmental Affairs (Indiana University)

experience:
  - Engineer at Deerns Consulting Engineers

questions:
  -
    q: What I like to do outside working hours...

    a:
      I love sports that interact with the elements of nature. I practice
      windsurfing, snowboarding and paragliding, sports in which you
      really learn to respect the beauty and power of nature.
  -
    q: Which problem I would like to solve...

    a:
      One of the main issues of not only the energy problem but of many other
      problems in the world is the growing population. Although this is a problem
      with sensitive ethical questions, I do feel a truly sustainable society can
      only be realized when this problem is tackled.
  -
    q: What is your (educational) background?

    a:
      I studied Systems Engineering, Policy Analysis and Management at the
      Delft University of Technology. During this master course I took classes
      on different types of electricity production on the various faculties in
      the university. I have also studied a semester at the School of Public
      and Environmental Affairs at the Indiana University in the USA and
      participated in a project on indicators of sustainability at the University
      of Queensland in Brisbane, Australia.

  -
    q: What are your responsibilities at Quintel Intelligence?

    a:
      Within Quintel I think about how reality can best be simulated in our model
      without oversimplifying the complex relations that exist in our energy system.
      Besides model development I also try to consider Quintel's own environmental
      impact in my function as procurement manager.

  -
    q: Tell us a fun fact

    a:
      It took the world 3,000,000 years to produce the amount of oil that we use
      this year.
