development: &DEV

production: &PRODUCTION
    <<: *DEV
    # airbrake_api_key: '03bc16d0ad22cb6680c0fad7a58c4582'
test:
    <<: *DEV
staging:
    <<: *PRODUCTION
    # airbrake_api_key: '64e97ea964161781f41d9d7e94c9c256'
