Applications:
  Professional: product:pro
  Light: product:light
  Mobile Game: product:quest

Partners:

Background:
  Open Source: open_source
  API: api
  Known Issues: known_issues
  Quality Control: quality_control
  Publications: http://refman.energytransitionmodel.com/
  Documentation: http://github.com/quintel/documentation
  Units: units
