Applications:
  Professional: product:pro
  Light: product:light
  Mobile Game: product:quest

Partners:

Press Releases: press_releases

Background:
  Open Source: open_source
  API: api
  Education: http://onderwijs.quintel.com
  Known Issues: known_issues
  Quality Control: quality_control
  Publications: http://refman.energytransitionmodel.com/
  Documentation: http://github.com/quintel/documentation
  Units: units
