Applications:
  Professional: product:pro
  Light: product:light

Background:
  Open Source: open_source
  API: api
  Quality Control: quality_control
  Education: https://edu.quintel.com/
  Publications: http://refman.energytransitionmodel.com/
  Documentation: https://docs.energytransitionmodel.com/
  Units: units

Partners:
