-
  name: GasTerra
  key:  gasterra
  kind: primary
-
  name: Shell
  key:  shell
  kind: primary
-
  name: Alliander
  key:  alliander
  kind: primary
-
  name: AT Kearney
  key:  atkearney
  kind: knowledge
-
  name: Clingendael
  key:  clingendael
  kind: knowledge
-
  name: Delta
  key:  delta
  kind: primary
-
  name: ECN
  key:  ecn
  kind: knowledge
-
  name: EDI
  key:  edi
  kind: education
-
  name: Eneco
  key:  eneco
  kind: primary
-
  name: Energy Valley
  key:  energyvalley
  kind: education
-
  name: Enexis
  key:  enexis
  kind: primary
-
  name: InterProvinciaal Overleg (IPO)
  key:  ipo
  kind: primary
-
  name: Jouw Energie van Morgen
  key:  jouwenergievanmorgen
  kind: education
-
  name: NDV KEMA
  key:  kema
  kind: knowledge
-
  name: Milieu Centraal
  key:  milieucentraal
  kind: knowledge
-
  name: Netbeheer Nederland
  key:  netbeheer
  kind: primary
-
  name: Nyenrode
  key:  nyenrode
  kind: education
-
  name: Philips
  key:  philips
  kind: primary
-
  name: Stichting Natuur en Milieu
  key:  snm
  kind: knowledge
-
  name: StedIn
  key:  stedin
  kind: primary
-
  name: TenneT
  key:  tennet
  kind: primary
-
  name: Uneto VNI
  key:  unetovni
  kind: primary
-
  name: Vopak
  key:  vopak
  kind: primary
-
  name: Visser & Smit Hanab
  key:  vshanab
  kind: primary
-
  name: Brandenburg
  key:  brandenburg
  kind: government
-
  name: Ministerie van Economische Zaken
  key:  minez
  kind: primary
-
  name: Gemeente Amsterdam
  key:  amsterdam
  kind: primary
-
  name: Gemeente Groningen
  key:  groningen
  kind: government
-
  name: Gemeente Ameland
  key:  ameland
  kind: government
-
  name: EnergieNederland
  key:  energienederland
  kind: company
-
  name: Urgenda
  key:  urgenda
  kind: primary
-
  name: e.on
  key:  eon
  kind: primary
-
  name: CGI
  key:  cgi
  kind: primary
-
  name: Essent
  key:  essent
  kind: primary
-
  name: Gasunie
  key:  gasunie
  kind: primary
-
  name: Ecofys
  key:  ecofys
  kind: knowledge
-
  name: warmtepompplein.nl
  key:  warmtepompplein
  kind: knowledge
-
  name: EPN
  key:  epn
  kind: education
-
  name: Het Platform Beroepsonderwijs
  key:  hpbodeb
  kind: education
-
  name: Uitleg & Tekst
  key:  uitlegtekst
  kind: education
-
  name: Belevenisonderwijs
  key:  belevenisonderwijs
  kind: education
-
  name: Energy Club Delft
  key:  energy_club
  kind: education
-
  name: ABN Amro
  key:  abnamro
  kind: primary
-
  name: Lesmodule De Energiecrisis
  key:  energiecrisis
  kind: education
-
  name: Berenschot
  key:  berenschot
  kind: primary
-
  name: Browserstack
  key:  browserstack
  kind: knowledge
-
  name: Stichting Sanegeest
  key:  sanegeest
  kind: primary
