-
  name: GasTerra
  key:  gasterra
  kind: primary
-
  name: Alliander
  key:  alliander
  kind: primary
-
  name: Clingendael
  key:  clingendael
  kind: knowledge
-
  name: DNWG
  key:  dnwg
  kind: primary
-
  name: ECN
  key:  ecn
  kind: knowledge
-
  name: EDI
  key:  edi
  kind: education
-
  name: Eneco
  key:  eneco
  kind: primary
-
  name: Energy Valley
  key:  energyvalley
  kind: education
-
  name: Enexis
  key:  enexis
  kind: primary
-
  name: InterProvinciaal Overleg (IPO)
  key:  ipo
  kind: primary
-
  name: NDV KEMA
  key:  kema
  kind: knowledge
-
  name: Netbeheer Nederland
  key:  netbeheer
  kind: primary
-
  name: Nyenrode
  key:  nyenrode
  kind: education
-
  name: Stichting Natuur en Milieu
  key:  snm
  kind: knowledge
-
  name: StedIn
  key:  stedin
  kind: primary
-
  name: TenneT
  key:  tennet
  kind: primary
-
  name: Brandenburg
  key:  brandenburg
  kind: government
-
  name: Ministerie van Economische Zaken en Klimaat
  key:  minez
  kind: primary
-
  name: Gemeente Amsterdam
  key:  amsterdam
  kind: primary
-
  name: Gemeente Groningen
  key:  groningen
  kind: primary
-
  name: Gemeente Ameland
  key:  ameland
  kind: government
-
  name: EnergieNederland
  key:  energienederland
  kind: company
-
  name: Urgenda
  key:  urgenda
  kind: primary
-
  name: e.on
  key:  eon
  kind: primary
-
  name: CGI
  key:  cgi
  kind: primary
-
  name: Essent
  key:  essent
  kind: primary
-
  name: Gasunie
  key:  gasunie
  kind: primary
-
  name: Ecofys
  key:  ecofys
  kind: knowledge
-
  name: warmtepompplein.nl
  key:  warmtepompplein
  kind: knowledge
-
  name: EPN
  key:  epn
  kind: education
-
  name: Het Platform Beroepsonderwijs
  key:  hpbodeb
  kind: education
-
  name: Uitleg & Tekst
  key:  uitlegtekst
  kind: education
-
  name: Belevenisonderwijs
  key:  belevenisonderwijs
  kind: education
-
  name: Energy Club Delft
  key:  energy_club
  kind: education
-
  name: Lesmodule De Energiecrisis
  key:  energiecrisis
  kind: education
-
  name: Berenschot
  key:  berenschot
  kind: primary
-
  name: Browserstack
  key:  browserstack
  kind: knowledge
-
  name: Stichting Sanegeest
  key:  sanegeest
  kind: primary
-
  name: Provincie Gelderland
  key:  gelderland
  kind: primary
-
  name: Stad Antwerpen
  key:  antwerpen
  kind: primary
-
  name: Provincie Friesland
  key:  friesland
  kind: primary
-
  name: Provincie Flevoland
  key:  flevoland
  kind: primary
-
  name: Over Morgen
  key:  overmorgen
  kind: company
-
  name: Witteveen + Bos
  key:  witteveen
  kind: company
-
  name: E&E Advies
  key:  eeadvies
  kind: primary
-
  name: Gelders Energieakkoord
  key:  gea
  kind: primary
-
  name: Greenpeace
  key:  greenpeace
  kind: primary
-
  name: Saxion Hogeschool
  key:  saxion
  kind: education
-
  name: Provincie Groningen
  key:  pgroningen
  kind: government
-
  name: TNO
  key: tno
  kind: primary
-
  name: TKI
  key: tki
  kind: primary
