-
  name:       Alexander Wirtz
  key:        alex
  title:      Partner
-
  name:       Anthony Williams
  key:        antw
  title:      Developer
-
  name:       John Kerkhoven
  key:        john
  title:      Managing Partner
-
  name:       Chael Kruip
  key:        chael
  title:      Senior Modeler
-
  name:       Dennis Schoenmakers
  key:        dennis
  title:      Partner
-
  name:       Wouter Meyers
  key:        wouter
  title:      Project manager
-
  name:       Mark den Heijer
  key:        mark
  title:      Project manager
-
  name:       Sebastian Burkhard
  key:        sebi
  title:      Developer
-
  name:       Paolo Zaccagnini
  key:        paolo
  title:      Developer
-
  name:       Jesse Kerkhoven
  key:        jesse
  title:      Developer
-
  name:       Chris Laumans
  key:        chris
  title:      Project Manager
-
  name:       Wouter van Lelyveld
  key:        wvl
  title:      Modeler
-
  name:       Jeroen Alsem
  key:        jeroen
  title:      Intern
-
  name:       Nikki Brormann
  key:        nikki
  title:      Office Manager
