-
  date:     2013-02-06
  author:   john
  key:      we-moeten-nadenken-over-het-verschil-tussen-transitie-en-traditie
  title:    "We moeten nadenken over het verschil tussen transitie en traditie"
  language: Dutch

-
  date:     2013-01-15
  author:   john
  key:      ruim-5-mrd-euro-aan-onnodige-kosten-door-onzuinige-tv-kastjes
  title:    "Ruim 5 mrd euro aan onnodige kosten door onzuinige tv-kastjes"
  language: Dutch

-
  date:     2012-11-23
  author:   john
  key:      vrolijke-en-sombere-gedachten-over-de-energietoekomst
  title:    "Vrolijke en sombere gedachten over de energietoekomst"
  language: Dutch
-
  date:     2012-11-05
  author:   john
  key:      iWat-als-het-IMF-gelijk-heeft-en-de-olieprijs-ster
  title:    "Wat als het IMF gelijk heeft en de olieprijs sterk stijgt?"
  language: Dutch
-
  date:     2012-10-16
  author:   john
  key:      we-zijn-allemaal-voorgeprogrammeerd-voor-hope-and-glory
  title:    "We zijn allemaal voorgeprogrammeerd voor ‘hope and glory’"
  language: Dutch
-
  date:     2012-09-27
  author:   john
  key:      blijkbaar-ben-ik-de-enige-gek-die-de-isolatie-van-zijn-ramen-nameet
  title:    "Blijkbaar ben ik de enige gek die de isolatie van zijn ramen nameet"
  language: Dutch
-
  date:     2012-08-29
  author:   john
  key:      watt-nu
  title:    "Watt Nu?!"
  language: Dutch
-
  date:     2012-07-16
  author:   john
  key:      werkgelegenheid-energiesector-gaat-toenemen
  title:    Werkgelegenheid energiesector gaat toenemen
  language: Dutch
-
  date:     2012-07-04
  author:   john
  key:      prominente-nederlanders-voor-vergaand-energiebeleid
  title:    Prominente Nederlanders voor vergaand energiebeleid
  language: Dutch
-
  date:     2012-08-23
  author:   john
  key:      de-oplossing-voor-het-schaarsteprobleem-ligt-bij-onszelf
  title:    De oplossing voor het schaarsteprobleem ligt bij onszelf
  language: Dutch
-
  date:     2012-04-12
  author:   john
  key:      tv-show-watt-nu-schudt-kijkers-wakker
  title:    "Tv show Watt Nu?! schudt kijkers wakker"
  language: Dutch
-
  date:     2012-03-26
  author:   john
  key:      waarom-ik-mijn-klimaatinstallatie-heb-gehackt
  title:    Waarom ik mijn klimaatinstallatie heb gehackt
  language: Dutch
-
  date:     2012-08-16
  author:   john
  key:      geweldig-groen-gas
  title:    Geweldig groen gas
  language: Dutch
-
  date:     2012-02-10
  author:   john
  key:      onze-overheid-zet-in-op-innovatiecontracten-anderen-innoveren
  title:    Onze overheid zet in op innovatiecontracten. Anderen innoveren
  language: Dutch
-
  date:     2012-01-27
  author:   john
  key:      waarom-de-term-smart-grid-verkeerd-is
  title:    "Waarom de term 'smart grid' verkeerd is"
  language: Dutch
-
  date:     2012-01-12
  author:   john
  key:      de-overeenkomst-tussen-een-dijkdoorbraak-en-een-energiecrisis
  title:    De overeenkomst tussen een dijkdoorbraak en een energiecrisis
  language: Dutch
-
  date:     2011-11-01
  author:   john
  key:      nederlander-leeft-met-de-illusie-dat-onze-energie-schoon-is
  title:    Nederlander leeft met de illusie dat onze energie schoon is
  language: Dutch
-
  date:     2011-09-30
  author:   john
  key:      onze-energie-komt-van-franse-kerncentrales-en-russisch-gas
  title:    Onze energie komt van Franse kerncentrales en Russisch gas
  language: Dutch
-
  date:     2011-09-16
  author:   john
  key:      energietransitie-vraagt-een-ongekende-inspanning
  title:    Energietransitie vraagt een ongekende inspanning
  language: Dutch
-
  date:     2011-08-31
  author:   john
  key:      per-ongeluk-een-sauna-in-mijn-kelder
  title:    Per ongeluk een sauna in mijn kelder
  language: Dutch
-
  date:     2011-07-18
  author:   john
  key:      duitsers-in-opstand-tegen-biobrandstof
  title:    Duitsers in opstand tegen biobrandstof
  language: Dutch
-
  date:     2011-07-07
  author:   john
  key:      kernenergie-ik-begrijp-het-niet
  title:    "Kernenergie: ik begrijp het niet"
  language: Dutch
-
  date:     2011-06-28
  author:   john
  key:      energierapport-2011-geen-verantwoording-en-visie
  title:    "Energierapport 2011: geen verantwoording en visie"
  language: Dutch
-
  date:     2011-06-21
  author:   john
  key:      energiewereld-kan-vraag-niet-meer-bijhouden
  title:    Energiewereld kan vraag niet meer bijhouden
  language: Dutch
