-
  medium: presentatie
  release_type: dagblad
  release_date: 2009-04-16
  link: /media/parilintrospeech.pdf
  title: Introductie Energietransitiemodel door John Kerkhoven
-
  medium: presentatie
  release_type: magazine
  release_date: 2013-07-08
  link: /media/verzineenswat.pdf
  title: Frans van Camp accepts internship at QI
