-
  medium: presentatie
  release_type: magazine
  release_date: 2009-04-16 00:00:00
  link: /media/16parilintrospeech.pdf
  title: Introductie Energietransitiemodel door John Kerkhoven
-
  medium: persbericht
  release_type: magazine
  release_date: 2009-04-02 00:00:00
  link: /media/Persuitnodiging_versie_6_aprilb.pdf
  title: Officiële lancering van Energietransitiemodel door Burgemeester Job Cohen
-
  medium: Telegraaf
  release_type: dagblad
  release_date: 2009-04-16 00:00:00
  link: /media/Telegraaf-DuurzamerMetEenPaarMuisklikken-20090416.pdf
  title: Duurzamer met een paar muisklikken
-
  medium: Metro
  release_type: dagblad
  release_date: 2009-04-17 00:00:00
  link: /media/20090417-Metro-Burgemeester_Cohen_lanceert_energiemodel.pdf
  title: Burgemeester Cohen lanceert energiemodel
-
  medium: Energeia
  release_type: dagblad
  release_date: 2009-04-17 00:00:00
  link: /media/20090417-Energiea_art1.pdf
  title: Computermodel laat iedereen Kiotootje spelen
-
  medium: Energeia
  release_type: dagblad
  release_date: 2009-04-17 00:00:00
  link: /media/20090417-Energiea_art2.pdf
  title: Europese uitbreiding in voorbereiding
-
  medium: EnergieRaad
  release_type: dagblad
  release_date: 2009-04-27 00:00:00
  link: /media/20090427_Energieraad.pdf
  title: "'Spel': zelf energievoorziening van de toekomst bepalen"
-
  medium: Energierecht
  release_type: magazine
  release_date: 2009-05-04 00:00:00
  link: /media/energierecht.pdf
  title: Energietransitiemodel
-
  medium: Amsterdam Innovatie Monitor
  release_type: dagblad
  release_date: 2009-05-01 00:00:00
  link: /media/Een_nieuw_initiatief.pdf
  title: Een nieuw initiatief op www.energietransitiemodel.nl
-
  medium: Groenebrandstof.nl
  release_type: dagblad
  release_date: 2009-05-10 00:00:00
  link: /media/greenfuel.pdf
  title: Energy Transition Model for the Netherlands
-
  medium: SenterNovem
  release_type: dagblad
  release_date: 2009-05-11 00:00:00
  link: /media/SenterNovem_EnergieTransitie.pdf
  title: Computermodel maakt energietransitie inzichtelijk
-
  medium: Contxt
  release_type: dagblad
  release_date: 2009-04-25 00:00:00
  link: /media/Enexis_Transitiemodel_helpt_knopen_doorhakken.jpg
  title: Transitiemodel helpt knopen doorhakken
-
  medium: Het Financieele Dagblad
  release_type: dagblad
  release_date: 2009-05-20 00:00:00
  link: /media/FD_200509_Klikken_voor_een_betere_toekomst.pdf
  title: "Energiemodel: Klikken voor een betere toekomst"
-
  medium: Automatisering Gids
  release_type: dagblad
  release_date: 2009-05-12 00:00:00
  link: /media/20090512-Automatiseringsgids.pdf
  title: Gratis computermodel moet energiedebat oliën
-
  medium: Quintessence
  release_type: magazine
  release_date: 2009-06-01 00:00:00
  link: /media/q7_01_energietransitiemodel.pdf
  title: Quintel’s Energietransitiemodel
-
  medium: "Congreskrant: Vaart in Verduurzaming (pag. 13)"
  release_type: magazine
  release_date: 2009-05-14 00:00:00
  link: /media/Congreskrant Vaart in Verduurzaming.pdf
  title: Quintel maakt energiediscussie beheersbaar
-
  medium: EnergieSquare (FD Intelligence - Shell)
  release_type: magazine
  release_date: 2009-06-10 00:00:00
  link: /media/Uitnodiging_Energie_Cafe.pdf
  title: Hoe ziet jouw energietoekomst eruit?
-
  medium: KernVisie
  release_type: magazine
  release_date: 2009-06-16 00:00:00
  link: /media/KernVisie.pdf
  title: Vorm jezelf een beeld de toekomstige energietransitie (pag. 7).
-
  medium: Shell/FD
  release_type: magazine
  release_date: 2009-06-30 00:00:00
  link: /media/Energiecafe_Shell_FD_en_het_Energietransitiemodel.pdf
  title: Vier toekomstscenario's van het Energiecafé van Shell en FD Intelligence
-
  medium: Shell Venster
  release_type: magazine
  release_date: 2009-07-01 00:00:00
  link: /media/Shell_Venster_ETM.pdf
  title: Vijf over twaalf
-
  medium: Energy Square
  release_type: magazine
  release_date: 2009-06-30 00:00:00
  link: /media/EnergySquare.pdf
  title: Wat is de ideale energietoekomst van Nederland?
-
  medium: European Energy Review
  release_type: magazine
  release_date: 2009-07-07 00:00:00
  link: /media/EAR.pdf
  title: Playing Energy Minister
-
  medium: Nieuwsbrief Milieu & Economie
  release_type: magazine
  release_date: 2009-07-13 00:00:00
  link: /media/NME2009-3.pdf
  title: Energietransitiemodel moet energietransitie versnellen
-
  medium: (blog) Herberg PV
  release_type: dagblad
  release_date: 2009-08-08 00:00:00
  link: /media/herbergpv.nl.pdf
  title: Kruip in de huid van Maria v/d Hoeven (EZ)
-
  medium: Dutch Power
  release_type: dagblad
  release_date: 2009-04-27 00:00:00
  link: /media/SpeedingUpWithDutchPower.pdf
  title: Speeding Up With Dutch Power
-
  medium: De Volkskrant
  release_type: dagblad
  release_date: 2009-08-08 00:00:00
  link: /media/Volkskrant_Het_lastige_spel_van_de_duurzame_Maria.pdf
  title: Het lastige spel van de duurzame Maria
-
  medium: Urgenda
  release_type: dagblad
  release_date: 2009-09-09 00:00:00
  link: /media/UrgendaAankondigingETMv2.pdf
  title: Release Energietransitiemodel versie 2.0
-
  medium: ClubGreen
  release_type: dagblad
  release_date: 2009-09-05 00:00:00
  link: /media/20090905-ClubGreen-Interview.pdf
  title: Interview met John Kerkhoven over het Energietransitiemodel
-
  medium: Het Financieele Dagblad
  release_type: dagblad
  release_date: 2009-09-09 00:00:00
  link: /media/20090909-FD-Nederlands_hebben_veel_misvattingen.pdf
  title: Nederlanders hebben veel misvattingen over energie
-
  medium: IPO
  release_type: magazine
  release_date: 2009-10-21 00:00:00
  link: /media/Werkconferentie_IPO.pdf
  title: Werkconferentie concretiseert provinciale inzet op energietransitie
-
  medium: Logica
  release_type: magazine
  release_date: 2009-11-01 00:00:00
  link: /media/Logica.pdf
  title: Logica is making electric cars a success
-
  medium: JMA - School nieuwsbrief
  release_type: dagblad
  release_date: 2009-09-09 00:00:00
  link: /media/JMA-school nieuwsbrief78.pdf
  title: Energievoorziening
-
  medium: EnergieAdvies
  release_type: dagblad
  release_date: 2009-12-15 00:00:00
  link: /media/energieadvies.pdf
  title: Het Enegietransitie-Online Spel
-
  medium: Verbouwstof.nl
  release_type: dagblad
  release_date: 2009-11-12 00:00:00
  link: /media/verbouwstof.nl.pdf
  title: Hoe verwarm ik straks mijn huis?
-
  medium: GroundsForChange
  release_type: dagblad
  release_date: 2010-01-07 00:00:00
  link: /media/GroundsForChange.pdf
  title: Energietransitiemodel
-
  medium: Passie voor Systemen
  release_type: dagblad
  release_date: 2009-12-07 00:00:00
  link: /media/passie_voor_systemen.pdf
  title: Energiesysteem in de overgang
-
  medium: GasTerra
  release_type: dagblad
  release_date: 2010-03-29 00:00:00
  link: /media/gasterra_transitie_jaarprijs.pdf
  title: Transitie jaarprijs
-
  medium: Low impact man (weblog)
  release_type: dagblad
  release_date: 2010-03-27 00:00:00
  link: /media/lowimpactman.pdf
  title: Blackout in Utrecht
-
  medium: Dutch Power
  release_type: dagblad
  release_date: 2010-04-01 00:00:00
  link: /media/Dutch Power.pdf
  title: De feiten achter de aannames
-
  medium: Consultancy.nl
  release_type: magazine
  release_date: 2010-08-05 00:00:00
  link: /media/quintop.jpg
  title: "Energiecongres trekt conclusie: geen duurzaamheid zonder aardgas"
-
  medium: EnergieRaad
  release_type: magazine
  release_date: 2010-08-05 00:00:00
  link: /media/energieraad.jpg
  title: Verken de toekomst met Quintel en GasTerra
-
  medium: FD Selections
  release_type: magazine
  release_date: 2010-08-05 00:00:00
  link: /media/fd_selections.jpg
  title: Verken de toekomst met Quintel en GasTerra
-
  medium: GasTerra
  release_type: magazine
  release_date: 2010-08-03 00:00:00
  link: /media/gasterra_press_release.jpg
  title: Quintel en GasTerra presenteren online rekenmodel voor energie- en klimaatvraagstuk
-
  medium: EPN
  release_type: magazine
  release_date: 2010-09-21 00:00:00
  link: /media/epn.jpg
  title: EPN stelt gratis project energietransitie beschikbaar voor alle VO-scholen
-
  medium: SenterNovem
  release_type: magazine
  release_date: 2010-09-15 00:00:00
  link: /media/regieorgaan.jpg
  title: Nieuwe versie Energietransitiemodel gelanceerd
-
  medium: Consultancy
  release_type: magazine
  release_date: 2010-09-16 00:00:00
  link: /media/consultancy.jpg
  title: Quintel verfijnt Energietransitiemodel
-
  medium: Hogeschool Zuyd
  release_type: magazine
  release_date: 2010-09-13 00:00:00
  link: /media/zuyd.jpg
  title: 50 Internationale wetenschappers spreken tijdens SB10 conferentie Hogeschool Zuyd
-
  medium: Interprovinciaal Overleg
  release_type: magazine
  release_date: 2010-09-22 00:00:00
  link: /media/ipo.png
  title: Provincies concretiseren duurzame energiedoelen
-
  medium: Vives
  release_type: magazine
  release_date: 2010-09-24 00:00:00
  link: /media/vives.png
  title: Uitgeverij EPN maakt gratis project energietransitie voor álle VO-scholen
-
  medium: Energie Overheid
  release_type: magazine
  release_date: 2010-09-24 00:00:00
  link: /media/energieoverheid.jpg
  title: Provincies actualiseren duurzame energie scenario’s
-
  medium: Energeia
  release_type: magazine
  release_date: 2010-09-27 00:00:00
  link: /media/Energeia_enc_kema.pdf
  title: Quintel-directeur hoopt op ECN en Kema als nieuwe partners transitiemodel
-
  medium: Betawijs
  release_type: magazine
  release_date: 2010-09-27 00:00:00
  link: /media/betawijs_gratis_project.pdf
  title: Gratis project ‘Naar nieuwe energie’
-
  medium: Nieuwsbank
  release_type: magazine
  release_date: 2010-09-29 00:00:00
  link: /media/nieuws_bank_Energiecongres trekt conclusie- geen duurzaamheid zonder aardgas.pdf
  title: "Energiecongres trekt conclusie: geen duurzaamheid zonder aardgas"
-
  medium: Geoplein
  release_type: magazine
  release_date: 2010-09-30 00:00:00
  link: /media/geoplein_Energietransitiemodel (ETM).pdf
  title: Energietransitiemodel (ETM)
-
  medium: Hogeschool Zuyd
  release_type: magazine
  release_date: 2010-09-18 00:00:00
  link: http://www.hszuyd.nl/view_news.jsp?content=214913
  title: Startschot voor Euregio 0-impact regio
-
  medium: Nederland krijgt nieuwe energie
  release_type: 
  release_date: 2011-01-03 00:00:00
  link: /media/nl_krijgt_nieuwe_energie.pdf
  title: Zelf spelen met het ‘100% duurzaam in 2050’ scenario via Energietransitiemodel.nl
-
  medium: not-online
  release_type: magazine
  release_date: 2010-12-07 00:00:00
  link: /media/not_online_Leerlingen maken energiebeleid tot 2040.pdf
  title: Leerlingen maken energiebeleid tot 2040
-
  medium: ECN
  release_type: magazine
  release_date: 2011-01-16 00:00:00
  link: /media/ECN werkt samen met Quintel Intelligence voor ondersteuning en verdere uitbouw van het energietransitiemodel.pdf
  title: ECN werkt samen met Quintel Intelligence voor ondersteuning en verdere uitbouw van het energietransitiemodel.
-
  medium: Opgewekt
  release_type: 
  release_date: 2011-03-01 00:00:00
  link: /media/ETm doo john kerkhoven.pdf
  title: Energietransitiemodel door John van Kerkhoven
-
  medium: Energie Gids
  release_type: 
  release_date: 2011-02-28 00:00:00
  link: /media/Derde editie GasTerra Transitie Jaarprijs van start.pdf
  title: Derde editie GasTerra Transitie Jaarprijs van start
-
  medium: NMF Groningen
  release_type: 
  release_date: 2011-03-07 00:00:00
  link: /media/Noordelijk Klimaat Perspectief duurzame wegwijzer voor energievoorziening Noord-Nederland.pdf
  title: Noordelijk Klimaat Perspectief duurzame wegwijzer voor energievoorziening Noord-Nederland
-
  medium: YouTube
  release_type: 
  release_date: 2011-05-08 00:00:00
  link: http://www.youtube.com/watch?v=9lkInwYNkgM
  title: GasTerra Energietransitiemodel
-
  medium: Kennislink
  release_type: 
  release_date: 2011-05-03 00:00:00
  link: /media/Energiemix in 2030- elektriciteit en waterstof.pdf
  title: "Energiemix in 2030: elektriciteit en waterstof?"
-
  medium: Duurzame Student
  release_type: 
  release_date: 2011-05-15 00:00:00
  link: /media/Transitie Inspiratiesessie Gasterra Challenge.pdf
  title: Transitie Inspiratiesessie (Gasterra Challenge)
-
  medium: De nacht van de kunstwetenschap
  release_type: magazine
  release_date: 2011-05-21 00:00:00
  link: /media/Discovery Truck.pdf
  title: Discovery Truck
-
  medium: Metro
  release_type: dagblad
  release_date: 2011-05-23 00:00:00
  link: /media/mens_is_innovatief_als_het_nodig_is.pdf
  title: Mens is inventief als het nodig is
-
  medium: People Planet Profit
  release_type: magazine
  release_date: 2011-06-01 00:00:00
  link: /media/boodschappenbriefje_voor_rutten.pdf
  title: "Energy Transition Model: Boodschappenbriefje voor Rutte"
-
  medium: Energiepodium
  release_type: magazine
  release_date: 2011-05-30 00:00:00
  link: /media/Energiewereld kan vraag niet meer bijhouden.pdf
  title: Energiewereld kan vraag niet meer bijhouden
-
  medium: People Planet Profit
  release_type: magazine
  release_date: 2011-06-12 00:00:00
  link: /media/Ben_jij_een_5_over_12_denker.pdf
  title: "P+Live@Night: Ben jij een 5 over 12-denker?"
-
  medium: Qu3
  release_type: magazine
  release_date: 2011-08-29 22:00:00
  link: http://f.cl.ly/items/0U1X3m3H1P460X2B110H/Schermafbeelding%202011-08-30%20om%2013.48.38.png
  title: Energietransitiemodel
-
  medium: Sustainability Congres
  release_type: magazine
  release_date: 2011-11-29 23:00:00
  link: http://www.sustainability-congres.nl/themasessie2/
  title: Hoe gaat Nederland de Europese duurzaamheids doelstellingen voor 2020 behalen?
-
  medium: Dwars
  release_type: magazine
  release_date: 2011-04-13 22:00:00
  link: http://www.dwars.org/sites/dwars.org/files/Energievisie%20DWARS.pdf
  title: DWARS presenteert energievisie
-
  medium: Nationale Jongerenraad
  release_type: 
  release_date: 2011-09-27 22:00:00
  link: http://njr.nl/index.php?option=com_k2&view=item&layout=item&id=138&Itemid=74
  title: GASTERRA CHALLENGE
-
  medium: Energiepodium
  release_type: magazine
  release_date: 2011-09-15 22:00:00
  link: http://www.energiepodium.nl/nieuws/item/energietransitie-vraagt-een-ongekende-inspanning
  title: Energietransitie vraagt een ongekende inspanning
-
  medium: Energiepodium
  release_type: magazine
  release_date: 2011-08-30 22:00:00
  link: http://www.energiepodium.nl/nieuws/item/per-ongeluk-een-sauna-in-mijn-kelder
  title: Per ongeluk een sauna in mijn kelder
-
  medium: Energiepodium
  release_type: magazine
  release_date: 2011-07-17 22:00:00
  link: http://www.energiepodium.nl/opinie/item/duitsers-in-opstand-tegen-biobrandstof
  title: Duitsers in opstand tegen biobrandstof
-
  medium: Energiepodium
  release_type: magazine
  release_date: 2011-07-06 22:00:00
  link: http://www.energiepodium.nl/nieuws/item/kernenergie-ik-begrijp-het-niet
  title: "Kernenergie: ik begrijp het niet"
-
  medium: VNO NCW
  release_type: magazine
  release_date: 2011-10-05 22:00:00
  link: http://www.vno-ncw.nl/SiteCollectionDocuments/Forumartikelen/Forum_1811_fossiel_16627.pdf
  title: Afscheid van fossiel kan
-
  medium: Metro Nieuws
  release_type: dagblad
  release_date: 2011-11-06 23:00:00
  link: http://www.metronieuws.nl/lifestyle/energy-mixer-laat-effect-van-gemaakte-keuzes-zien/SrZkkg!2rpB0qdhJJvr2/
  title: Energy Mixer laat effect van gemaakte keuzes zien
-
  medium: Nuon / Vattenfall
  release_type: dagblad
  release_date: 2011-10-31 23:00:00
  link: /media/ToekomstVanEnergie.pdf
  title: "Over de Toekomst van Energie: Experts aan het woord"
-
  medium: Energeia
  release_type: magazine
  release_date: 2011-12-06 23:00:00
  link: /media/Shell_gebruikt_Energietransitiemodel_bij_Energy_Circles.pdf
  title: Shell gebruikt Energietransitiemodel bij Energy Circles
-
  medium: De Terugkoppeling
  release_type: magazine
  release_date: 2012-02-20 23:00:00
  link: /media/20120221 Eindversie artikel Terugkoppeling Energietransitiemodel.jpg
  title: Leerlingen Techniek kunnen aan de slag met het Energietransitiemodel in de les
-
  medium: Metro
  release_type: magazine
  release_date: 2012-02-20 23:00:00
  link: /media/spelen_met_energietransitie.pdf
  title: Spelen met Energietransitie
-
  medium: EnergyFuture.nl
  release_type: magazine
  release_date: 2011-12-06 23:00:00
  link: /media/energycircle_7nov11.pdf
  title: "EnergyCircle: Energieverbruik in 2050"
-
  medium: energieoverheid.nl
  release_type: internet
  release_date: 2012-06-03 22:00:00
  link: /media/EnergieOverheid.nl_20120604_Geen hypotheekrenteaftrek meer.pdf
  title: “Geen hypotheekrenteaftrek meer op nieuwbouw”
-
  medium: Duurzaamnieuws.nl
  release_type: internet
  release_date: 2012-04-23 22:00:00
  link: /media/vvd_wil_vier_nieuwe_kerncentrales.pdf
  title: VVD wil vier nieuwe kerncentrales