file_name: Congreskrant_Vaart_in_Verduurzaming.pdf
title: Quintel maakt energiediscussie beheersbaar
medium: ! 'Congreskrant: Vaart in Verduurzaming (pag. 13)'
release_date: '2009-05-14'
release_type: magazine
key: 2009-05-14_congreskrantvaartinverduurzamingpag
