file_name: Energiecafe_Shell_FD_en_het_Energietransitiemodel.pdf
title: Vier toekomstscenario's van het Energiecafé van Shell en FD Intelligence
medium: Shell/FD
release_date: '2009-06-30'
release_type: magazine
key: 2009-06-30_shellfd
