file_name: 20090512_Automatiseringsgids.pdf
title: ! 'Gratis computermodel moet energiedebat oliën '
medium: Automatisering_Gids
release_date: '2009-05-12'
release_type: dagblad
key: 2009-05-12_automatiseringgids
