file_name: 20090905_ClubGreen_Interview.pdf
title: Interview met John Kerkhoven over het Energietransitiemodel
medium: ClubGreen
release_date: '2009-09-05'
release_type: dagblad
key: 2009-09-05_clubgreen
