file_name: 20090417_Metro_Burgemeester_Cohen_lanceert_energiemodel.pdf
title: Burgemeester Cohen lanceert energiemodel
medium: Metro
release_date: '2009-04-17'
release_type: dagblad
key: 2009-04-17_metro
