file_name: NME2009_3.pdf
title: Energietransitiemodel moet energietransitie versnellen
medium: "Nieuwsbrief Milieu & Economie"
release_date: '2009-07-13'
release_type: magazine
key: 2009-07-13_nieuwsbriefmilieueconomie
