file_name: Telegraaf_DuurzamerMetEenPaarMuisklikken_20090416.pdf
title: Duurzamer met een paar muisklikken
medium: Telegraaf
release_date: '2009-04-16'
release_type: dagblad
key: 2009-04-16_telegraaf
