file_name: Volkskrant_Het_lastige_spel_van_de_duurzame_Maria.pdf
title: Het lastige spel van de duurzame Maria
medium: De_Volkskrant
release_date: '2009-08-08'
release_type: dagblad
key: 2009-08-08_devolkskrant
