file_name: Persuitnodiging_versie_6_aprilb.pdf
title: Officiële lancering van Energietransitiemodel door Burgemeester Job Cohen
medium: persbericht
release_date: '2009-04-02'
release_type: magazine
key: 2009-04-02_persbericht
