file_name: 20090909_FD_Nederlands_hebben_veel_misvattingen.pdf
title: Nederlanders hebben veel misvattingen over energie
medium: Het_Financieele_Dagblad
release_date: '2009-09-09'
release_type: dagblad
key: 2009-09-09_hetfinancieeledagblad
