file_name: Een_nieuw_initiatief.pdf
title: Een nieuw initiatief op www.energietransitiemodel.nl
medium: Amsterdam Innovatie Monitor
release_date: '2009-05-01'
release_type: dagblad
key: 2009-05-01_amsterdaminnovatiemonitor
