file_name: Energeia_enc_kema.pdf
title: Quintel-directeur hoopt op ECN en Kema als nieuwe partners transitiemodel
medium: Energeia
release_date: '2010-09-27'
release_type: magazine
key: 2010-09-27_energeia
