file_name: http://www.hszuyd.nl/view_news.jsp?content=214913
title: Startschot voor Euregio 0-impact regio
medium: Hogeschool_Zuyd
release_date: '2010-09-18'
release_type: magazine
key: 2010-09-18_hogeschoolzuyd
