file_name: gasterra_press_release.jpg
title: Quintel en GasTerra presenteren online rekenmodel voor energie- en klimaatvraagstuk
medium: GasTerra
release_date: '2010-08-03'
release_type: magazine
key: 2010-08-03_gasterra
