file_name: zuyd.jpg
title: 50 Internationale wetenschappers spreken tijdens SB10 conferentie Hogeschool
  Zuyd
medium: Hogeschool_Zuyd
release_date: '2010-09-13'
release_type: magazine
key: 2010-09-13_hogeschoolzuyd
