file_name: Ben_jij_een_5_over_12_denker.pdf
title: "P+Live@Night: Ben jij een 5 over 12-denker?"
medium: People Planet Profit
release_date: '2011-06-12'
release_type: magazine
key: 2011-06-12_peopleplanetprofit
