file_name: ToekomstVanEnergie.pdf
title: ! 'Over de Toekomst van Energie: Experts aan het woord'
medium: Nuon / Vattenfall
release_date: '2011-11-01'
release_type: dagblad
key: 2011-11-01_nuonvattenfall
