file_name: http://www.energiepodium.nl/nieuws/item/kernenergie-ik-begrijp-het-niet
title: ! 'Kernenergie: ik begrijp het niet'
medium: Energiepodium
release_date: '2011-07-07'
release_type: magazine
key: 2011-07-07_energiepodium
