file_name: boodschappenbriefje_voor_rutten.pdf
title: "Energy Transition Model: Boodschappenbriefje voor Rutte"
medium: People Planet Profit
release_date: '2011-06-01'
release_type: magazine
key: 2011-06-01_peopleplanetprofit
