file_name: http://www.energiepodium.nl/nieuws/item/per-ongeluk-een-sauna-in-mijn-kelder
title: Per ongeluk een sauna in mijn kelder
medium: Energiepodium
release_date: '2011-08-31'
release_type: magazine
key: 2011-08-31_energiepodium
