file_name: http://njr.nl/index.php?option=com_k2&view=item&layout=item&id=138&Itemid=74
title: GASTERRA CHALLENGE
medium: Nationale_Jongerenraad
release_date: '2011-09-28'
release_type: undefined
key: 2011-09-28_nationalejongerenraad
