file_name: http://f.cl.ly/items/0U1X3m3H1P460X2B110H/Schermafbeelding%202011-08-30%20om%2013.48.38.png
title: Energietransitiemodel
medium: Qu3
release_date: '2011-08-30'
release_type: magazine
key: 2011-08-30_qu3
