file_name: http://www.energiepodium.nl/nieuws/item/energietransitie-vraagt-een-ongekende-inspanning
title: Energietransitie vraagt een ongekende inspanning
medium: Energiepodium
release_date: '2011-09-16'
release_type: magazine
key: 2011-09-16_energiepodium
