file_name: http://www.sustainability-congres.nl/themasessie2/
title: Hoe gaat Nederland de Europese duurzaamheids doelstellingen voor 2020 behalen?
medium: Sustainability Congres
release_date: '2011-11-30'
release_type: magazine
key: 2011-11-30_sustainabilitycongres
