file_name: http://www.energiepodium.nl/opinie/item/duitsers-in-opstand-tegen-biobrandstof
title: Duitsers in opstand tegen biobrandstof
medium: Energiepodium
release_date: '2011-07-18'
release_type: magazine
key: 2011-07-18_energiepodium
