file_name: Shell_gebruikt_Energietransitiemodel_bij_Energy_Circles.pdf
title: Shell gebruikt Energietransitiemodel bij Energy Circles
medium: Energeia
release_date: '2011-12-07'
release_type: magazine
key: 2011-12-07_energeia
