file_name: http://www.dwars.org/sites/dwars.org/files/Energievisie%20DWARS.pdf
title: DWARS presenteert energievisie
medium: Dwars
release_date: '2011-04-14'
release_type: magazine
key: 2011-04-14_dwars
