file_name: ECN_werkt_samen_met_Quintel_Intelligence_voor_ondersteuning_en_verdere_uitbouw_van_het_energietransitiemodel.pdf
title: "ECN werkt samen met Quintel Intelligence voor ondersteuning en verdere uitbouw
    van het energietransitiemodel."
medium: ECN
release_date: '2011-01-16'
release_type: magazine
key: 2011-01-16_ecn
