file_name: http://www.vno-ncw.nl/SiteCollectionDocuments/Forumartikelen/Forum_1811_fossiel_16627.pdf
title: Afscheid van fossiel kan
medium: VNO_NCW
release_date: '2011-10-06'
release_type: magazine
key: 2011-10-06_vnoncw
