file_name: 20120221_Eindversie_artikel_Terugkoppeling_Energietransitiemodel.jpg
title: Leerlingen Techniek kunnen aan de slag met het Energietransitiemodel in de
  les
medium: De_Terugkoppeling
release_date: '2012-02-21'
release_type: magazine
key: 2012-02-21_deterugkoppeling
