---
key: stokman
name: Frans Stokman
organization: RUG
function:
  nl: Professor Social Science Research Methodology
  en: Professor Social Science Research Methodology
scenario_id: 173612
event: ec2013