---
key: vanooijen
name: Frank van Ooijen
organization: Friesland Campina
function:
  nl: Corporate Director Sustainability and Communications
  en: Corporate Director Sustainability and Communications
scenario_id: 
event: ec2013