---
key: santen
name: Stijn Santen
organization: Triarri
function:
  nl: 'Leider Nederlandse dialoog binnen EU project R&Dialogue'
  en: 'Leader Dutch dialogue of EU project R&Dialogue'
scenario_id: 171781
event: ec2013