---
medium: goedkoopsteenergie.nl
release_type: magazine
release_date: 2014-05-15
link: http://www.goedkoopsteenergie.nl/betalen-we-in-de-toekomst-onze-energierekening-aan-google/
title: Betalen we in de toekomst onze energierekening aan Google?
