---
medium: Pakhuis de Zwijger
release_type: magazine
release_date: 2014-12-14
link: http://www.dezwijger.nl/127323/nl/de-circulaire-stad-14-energiereuzen 
title: "De Circulaire Stad #14: Energiereuze"
