---
medium: Bezinningsgroep Energie
release_type: magazine
release_date: 2014-05-01
link: http://www.bezinningsgroepenergie.nl/files/Jubileum/Essays_Symposium%20BG_def_reader.pdf
title: De Doorbraak van Duurzaam van niche naar mainstream
