---
medium: Utilities Magazine (members only)
release_type: magazine
release_date: 2015-02-10
link: http://www.utilities.nl/magazine/artikelen-abonnees/energiereuzen-onder-druk.150896.lynkx
title: Energiereuzen onder druk
