---
medium: SER
release_type: magazine
release_date:  2014-12-12
link: http://www.energieakkoordser.nl/~/media/files/energieakkoord/nieuwsberichten/2015/20141212-quintel.ashx
title: Hogere investeringen, lagere kosten en meer banen mede dankzij het Nationaal Energieakkoord
