---
medium: Philips
release_type: magazine
release_date: 2015-02-17
link: https://s3-eu-west-1.amazonaws.com/static.quintel.com/The-2015-Energy-Productivity-and-Economic-Prosperity-Index.pdf
title: Philips backs action to turn energy waste into increased productivity and economic growth
