---
medium: Philips
release_type: magazine
release_date: 2015-02-17
link: http://www.newscenter.philips.com/main/standard/news/press/2015/20150217-Philips-backs-action-to-turn-energy-waste-into-increased-productivity-and-economic-growth.wpd
title: Philips backs action to turn energy waste into increased productivity and economic growth
