---
medium: Philips
release_type: magazine
release_date: 2015-02-17
link: http://www.newscenter.philips.com/asset.aspx?alt=&p=http://www.newscenter.philips.com/pwc_nc/main/standard/resources/corporate/press/2015/Energy-Productivity-and-Economic-Prosperity-Index/The-2015-Energy-Productivity-and-Economic-Prosperity-Index.pdf
title: Philips backs action to turn energy waste into increased productivity and economic growth
