---
medium: Energeia
release_type: magazine
release_date: 2011-12-07
link: /media/Shell_gebruikt_Energietransitiemodel_bij_Energy_Circles.pdf
title: Shell gebruikt Energietransitiemodel bij Energy Circles
