---
medium: Het Financieele Dagblad
release_type: magazine
release_date: 2014-02-07
link: https://s3.amazonaws.com/images.static.quintel.com/20140207fd.pdf
title: SER-voorzitter bepleit 'nationale groeiagenda'
