---
medium: Alliander
release_type: internet
release_date: 2013-03-16
link: http://www.alliander.com/nl/alliander/innovatie/samen-innoveren/energietransitiemodel/index.htm
title: Verken de energietoekomst zelf