---
medium: Overstappen.nl
release_type: internet
release_date: 2014-03-17
link: http://www.overstappen.nl/nieuws/urgenda-100-duurzame-energie-2030-mogelijk/
title: Urgenda: 100% duurzame energie in 2030 mogelijk
