---
medium: De Terugkoppeling
release_type: magazine
release_date: 2012-02-21
link: /media/20120221 Eindversie artikel Terugkoppeling Energietransitiemodel.jpg
title: Leerlingen Techniek kunnen aan de slag met het Energietransitiemodel in de
  les
