---
medium: Het Financieele Dagblad
release_type: magazine
release_date: 2014-02-07
link: https://s3.amazonaws.com/images.static.quintel.com/20140207fd.pdf
title: SER-voorzitter Wiebe Draaier bepleit nationale groeiagenda en refereert daarbij aan de 40.000 Nederlanders die hun mening hebben gedeeld met het ETM
