---
key: 15
medium: ! 'Congreskrant: Vaart in Verduurzaming (pag. 13)'
release_type: magazine
release_date: 2009-05-14
link: /media/Congreskrant Vaart in Verduurzaming.pdf
title: Quintel maakt energiediscussie beheersbaar
