---
medium: Het Financieele Dagblad
release_type: magazine
release_date: 2013-12-28
link: https://s3-eu-west-1.amazonaws.com/static.quintel.com/20131228fd.pdf
title: Opmars groene energie dreigt vast te lopen
