---
medium: Watt connects
release_type: internet
release_date: 2013-04-28
link: http://www.wattconnects.com/agenda/interactieve-workshop-energietransitiemodel
title: Interactieve workshop Energietransitiemodel