---
medium: Energiepodium / Watt Nu
release_type: internet
release_date: 2013-02-26
link: /media/20130227 WN Tijd dat we kolencentrales nodig hebben is voorbij.pdf
title: Tijd dat we kolencentrales nodig hebben is voorbij