---
key: 42
medium: GasTerra
release_type: magazine
release_date: 2010-08-03
link: /media/gasterra_press_release.jpg
title: Quintel en GasTerra presenteren online rekenmodel voor energie- en klimaatvraagstuk
