---
medium: Energiepodium
release_type: magazine
release_date: 2011-08-31
link: http://www.energiepodium.nl/nieuws/item/per-ongeluk-een-sauna-in-mijn-kelder
title: Per ongeluk een sauna in mijn kelder
