---
key: 1
medium: persbericht
release_type: magazine
release_date: 2009-04-02
link: /media/Persuitnodiging_versie_6_aprilb.pdf
title: Officiële lancering van Energietransitiemodel door Burgemeester Job Cohen
