---
medium: De Correspondent
release_type: internet
release_date: 2014-03-14
link: https://decorrespondent.nl/848/honderd-procent-duurzame-energie-in-2030-kan-dat-/5420519456-b94ba36d
title: Honderd procent duurzame energie in 2030, kan dat?
