---
medium: Shell/FD
release_type: magazine
release_date: 2009-06-30
link: /media/Energiecafe_Shell_FD_en_het_Energietransitiemodel.pdf
title: Vier toekomstscenario's van het Energiecafé van Shell en FD Intelligence
