---
key: 66
medium: People Planet Profit
release_type: magazine
release_date: 2011-06-01
link: /media/boodschappenbriefje_voor_rutten.pdf
title: ! 'Energy Transition Model: Boodschappenbriefje voor Rutte'
