---
medium: Cobouw
release_type: internet
release_date: 2014-03-21
link: http://www.cobouw.nl/nieuws/duurzaamheid/2014/03/21/plan-urgenda-vraagt-nu-aanpakken-en-snel
title: Plan Urgenda vraagt nú aanpakken en snel
