---
medium: Energiepodium / Watt Nu
release_type: internet
release_date: 2013-04-30
link: /media/20130501 WN De energietransitie is over zijn kantelpunt heen.pdf
title: De energietransitie is over zijn kantelpunt heen