---
medium: HIER
release_type: internet
release_date: 2014-03-20
link: http://www.hier.nu/news/2169/urgenda-presenteert-inspirerende-visie-op-duurzame-energievoorziening
title: Urgenda presenteert inspirerende visie op duurzame energievoorziening
