---
key: 70
medium: Sustainability Congres
release_type: magazine
release_date: 2011-11-30
link: http://www.sustainability-congres.nl/themasessie2/
title: Hoe gaat Nederland de Europese duurzaamheids doelstellingen voor 2020 behalen?
