---
medium: Energiepodium / Watt Nu
release_type: internet
release_date: 2013-03-03
link: /media/20130304 WN Nederland zal Realpolitik bedrijven rond energie.pdf
title: Nederland zal Realpolitik bedrijven rond energie