---
medium: NU.nl
release_type: internet
release_date: 2014-03-14
link: http://www.nu.nl/economie/3725487/energie-kan-volledig-duurzaam-in-2030.html
title: 'Energie kan volledig duurzaam zijn in 2030'