---
medium: Energiepodium
release_type: magazine
release_date: 2011-07-18
link: http://www.energiepodium.nl/opinie/item/duitsers-in-opstand-tegen-biobrandstof
title: Duitsers in opstand tegen biobrandstof
