---
medium: ECN
release_type: magazine
release_date: 2011-01-16
link: /media/ECN werkt samen met Quintel Intelligence voor ondersteuning en verdere
  uitbouw van het energietransitiemodel.pdf
title: ECN werkt samen met Quintel Intelligence voor ondersteuning en verdere uitbouw
  van het energietransitiemodel.
