---
medium: Het Financieele Dagblad
release_type: magazine
release_date: 2013-12-28
link: https://s3.amazonaws.com/images.static.quintel.com/20140207fd.pdf
title: Opmars groene energie dreigt vast te lopen
