---
medium: urgenda
release_type: internet
release_date: 2014-03-25
link: http://www.youtube.com/watch?v=UMkehKZC3Kc&list=UUwUlayF7P2RnRHFz0_a1v9A&feature=share
title: Lancering Urgenda Rapport 2030 - Nederland op 100% duurzame energie in 2030.
