---
medium: Energiepodium
release_type: internet
release_date: 2014-03-21
link: http://www.energiepodium.nl/opinie/item/nieuw-rapport-urgenda-verfrissend-en-confronterend
title: "Nieuw rapport Urgenda verfrissend en confronterend"
