---
medium: Trouw
release_type: internet
release_date: 2014-03-14
link: http://www.trouw.nl/tr/nl/4332/Groen/article/detail/3612929/2014/03/14/In-2030-alles-op-zon-en-wind.dhtml
title: 'In 2030 alles op zon en wind'
