---
medium: De Telegraaf
release_type: internet
release_date: 2014-03-22
link: http://www.telegraaf.nl/mijnbedrijf/columnisten/ruudkoornstra/22405581/__Als_je_maar_wilt__.html
title: Als je maar wilt
