---
medium: Het Financieele Dagblad
release_type: dagblad
release_date: 2009-09-09
link: /media/20090909-FD-Nederlands_hebben_veel_misvattingen.pdf
title: Nederlanders hebben veel misvattingen over energie
