---
key: 78
medium: Metro Nieuws
release_type: dagblad
release_date: 2011-11-07
link: http://www.metronieuws.nl/lifestyle/energy-mixer-laat-effect-van-gemaakte-keuzes-zien/SrZkkg!2rpB0qdhJJvr2/
title: Energy Mixer laat effect van gemaakte keuzes zien
