---
medium: NKNE / SER
release_type: internet
release_date: 2013-04-15
link: http://nederland.krijgtnieuweenergie.nl/sites/default/files/20130416%20Scenario%20Rapport%20ETM%20voor%20de%20SER%20%28openbare%20versie%29.pdf?utm_source=Versnellers+online+versnellingsnetwerk&utm_campaign=a0f866aa4f-1K_test_burgerinitiatief&utm_medium=e
title: Terugkoppeling Scenario’s Gemaakt met het Energietransitiemodel T.b.v. het Nationaal Energieakkoord
