---
key: 73
medium: Energiepodium
release_type: magazine
release_date: 2011-09-16
link: http://www.energiepodium.nl/nieuws/item/energietransitie-vraagt-een-ongekende-inspanning
title: Energietransitie vraagt een ongekende inspanning
