---
title: Factchecker energie aflevering 1: het Energieakkoord is goed voor de economie
medium: SER
release_type: magazine
release_date: 2015-02-13
link: http://www.energieakkoordser.nl/nieuws/factchecker-energie/energieakkoord-goed-voor-economie.aspx
