---
medium: Pakhuis de Zwijger
release_type: magazine
release_date: 2014-04-14
link: http://www.dezwijger.nl/109674/nl/stadbericht-302-ten-strijde-tegen-de-energiecrisis
title: Ten strijde tegen de energiecrisis!
