---
medium: onderzoeksredectie.nl
release_type: magazine
release_date: 2014-09-15
link: http://www.onderzoeksredactie.nl/artikel/welke-opties-zijn-er-om-onder-het-russische-energiejuk-uit-te-komen/
title: Welke opties zijn er om onder het Russische energiejuk uit te komen?
